### ISSUE TITLE
Ordering the dashboards with the dashboard-group

### ISSUE THREAD

**Issue by saikrishna547** [splunk-terraform/terraform-provider-signalfx#127]
What we have is ordering the charts within the dashboard but not the dashboards when we do a terraform apply they are order randomly. So, It will be great if we can order those dashboards like overview first then followed by other dashboards that would be the best that everyone wants but its harder to swap once its built everytime.

**Comment by cory-signalfx** [comment]
Hello @saikrishna547,

Unfortunately this isn't possible with current API limitations. The dashboards are created in parallel, which means they will be added to the group in whatever order they are invoked. This not only results in an undefined order, but also occasional race conditions.

The fix for now is to run terraform with `-parallelism=1` when creating a dashboard group. This should result in the order being the same as the order in which the dashboards appear in the source file.

Sorry, this is an issue that is being tracked internally but has not yet hit the top of the list. I encourage you to ping SignalFx's support team to express your interest in this issue so that it can be prioritized for engineering.
