### ISSUE TITLE
Is it possible to link a detector to a chart?

### ISSUE THREAD

**Issue by DethAriel** [splunk-terraform/terraform-provider-signalfx#135]
Hey, and thank you a lot for the provider!

I was wondering if it is currently possible to link a signalfx chart to a detector? I looked through the docs for both `signalfx_detector` and `signalfx_time_chart`, and wasn't able to find any linking possible between them.

Would be nice to have that feature, cause SignalFX adds a good-looking green border around charts that have associated detectors :)

**Comment by cory-signalfx** [comment]
Hey there @DethAriel! You've probably seen the [Linking Detectors to Charts](https://docs.signalfx.com/en/latest/charts/linking-detectors.html) documentation. This clearly leaves you with questions like this one, since there's no signaling how to do this without the UI!

Luckily I can help, this feature is enabled via the SignalFlow function `alerts`. Here's an example:
```
A = data('CPUUtilization', filter=filter('namespace', 'AWS/EC2') and filter('stat', 'mean'), extrapolation='last_value', maxExtrapolations=5).publish(label='A')
B = alerts(detector_id='xxIDOfDetectorGoesHere').publish(label='B')
```

Hope that helps!

**Comment by glennpratt** [comment]
If you stumble on this with a chart and detector both defined in terraform, you are probably looking for an example like:

```terraform
  program_text = <<-EOF
    A = data('CPUUtilization', filter=filter('namespace', 'AWS/EC2') and filter('stat', 'mean'), extrapolation='last_value', maxExtrapolations=5).publish(label='A')
    B = alerts(detector_id='${signalfx_detector.my_detector.id}').publish(label='B')
    EOF
```
