### ISSUE TITLE
Missing open ended range(s) Error

### ISSUE THREAD

**Issue by brianpham** [splunk-terraform/terraform-provider-signalfx#162]
I am seeing this error when trying to create a single value chart. It should work according to this previously closed issue. https://github.com/terraform-providers/terraform-provider-signalfx/issues/97 

Can anyone help with this?

```
Error: Unexpected status code: 400: {
  "code" : 400,
  "message" : "Missing open ended range(s)"
}
```

```
resource "signalfx_single_value_chart" "recordings" {
  name        = "Recordings"

  program_text = <<-EOF
       redacted
        EOF

  color_by = "Scale"

  color_scale {
    color = "green"
    gt    = 60
    lte   = 100
  }

  color_scale {
    color = "yellow"
    gt    = 40
    lte   = 60
  }

  color_scale {
    color = "magenta"
    gte   = 0
    lte   = 40
  }
```

**Comment by cory-signalfx** [comment]
Hey @brianpham! The issue here is that the API wants to know what to do with your time series exceed those bounds. If you change it to:
```
color_scale {
    color = "green"
    gt    = 60
  }

  color_scale {
    color = "yellow"
    gt    = 40
    lte   = 60
  }

  color_scale {
    color = "magenta"
    lte   = 40
  }
```

then it should work. Note that I removed the lower bound on your magenta section (since anything below should be magenta) and the upper bound on your green (since > 60 is good).
