### ISSUE TITLE
Detectors created through terraform and seems like missing much of the info like the metric reported on and image is also not available 

### ISSUE THREAD

**Issue by saikrishna547** [splunk-terraform/terraform-provider-signalfx#181]

**Comment by saikrishna547** [comment]
<img width="645" alt="Screen Shot 2020-03-26 at 11 08 00 AM" src="https://user-images.githubusercontent.com/44275490/77681026-00d23900-6f52-11ea-9449-6a13692282fe.png">
These are the details that i am getting when i get an alert

**Comment by saikrishna547** [comment]
It should atleast report the metric name right?

**Comment by cory-signalfx** [comment]
Hey @saikrishna547! I am unsure why this would occur. I don't know of anything that the Terraform provider does that might trigger this to happen. Since it's more of a product feature can I encourage you to contact support and include the detector ID? We can investigate to see if it's something we need to improve/warn people about!

(Closing in favor of that approach, feel free to reopen if you find additional information that I can help with, otherwise I'll work with support.)
