### ISSUE TITLE
Unexpected status code:400 while creating signalfx_dashboard_group

### ISSUE THREAD

**Issue by andreamarinaro** [splunk-terraform/terraform-provider-signalfx#229]
Hi, I'm getting this error while trying to apply a simple dashboard_group resource via Terraform:
```
signalfx_dashboard_group.SLI: Creating...
Error: Unexpected status code: 400: {
  "code" : 400,
  "message" : "Failed to deserialize payload at: sf.domain.group.DashboardGroup[\"authorizedWriters\"]->sf.domain.AuthorizedWriters[\"users\"]->java.util.HashSet[0]"
}
```
This is my TF config:
```
data "aws_ssm_parameter" "dashboard_token" {
  name = "/prd/signalfx_dashboard_token"
  with_decryption = true
}

resource "signalfx_dashboard_group" "SLI" {
  name        = "SLI/SLO dashboard group"
  description = "Dashboard group for SLI/SLO metrics"
  authorized_writer_users = ["data.aws_ssm_parameter.dashboard_token.value"]
}
```
Any ideas? Thanks for helping

**Comment by cory-signalfx** [comment]
Hallo @andreamarinaro! Ik spreek een beetje Nederlands! 😄 

Two bits that may help:
  * `authorized_writer_users` expects the user id of a SignalFx user, as assigned by the API. Make sure that's what you are storing in that paramter.
  * The example given passes the string literal `"data.aws_ssm_parameter.dashboard_token.value"` instead of the underlying value you intended. Fixing this is different in Terraform [0.11](https://www.terraform.io/docs/configuration-0-11/interpolation.html) versus [0.12](https://www.terraform.io/docs/configuration/expressions.html#references-to-named-values). To save you a click in 0.12, you'd just remove the double quotes.

Once you correct either or both of the above you should make some progress. I'll leave this open in case you hit any snags.

Bedankt!

**Comment by andreamarinaro** [comment]
> 
> 
> Hallo @andreamarinaro! Ik spreek een beetje Nederlands! 😄
> 
> Two bits that may help:
> 
>     * `authorized_writer_users` expects the user id of a SignalFx user, as assigned by the API. Make sure that's what you are storing in that paramter.
> 
>     * The example given passes the string literal `"data.aws_ssm_parameter.dashboard_token.value"` instead of the underlying value you intended. Fixing this is different in Terraform [0.11](https://www.terraform.io/docs/configuration-0-11/interpolation.html) versus [0.12](https://www.terraform.io/docs/configuration/expressions.html#references-to-named-values). To save you a click in 0.12, you'd just remove the double quotes.
> 
> 
> Once you correct either or both of the above you should make some progress. I'll leave this open in case you hit any snags.
> 
> Bedankt!

Hey Cory, thanks a lot for your feedback!
I was trying to pass the access token instead, now I'm passing the user ID as it's returned by the API. 
The only thing, I had to stick with the [""] syntax cause, for that specific value, Terraform requires a set of strings and it seems this is the only way to pass the value along.

Thanks a lot for your help!
