### ISSUE TITLE
[Feature suggestion] Add ability to get User ID

### ISSUE THREAD

**Issue by Danielkem** [splunk-terraform/terraform-provider-signalfx#321]
When creating a [signalfx_team](https://registry.terraform.io/providers/splunk-terraform/signalfx/latest/docs/resources/team) you have the ability to add members by supplying a user id, it would be nice to be able to get the user id (unique Splunk member user id) associated with a user in azure.

Right now I need an external script which first queries azure to get an email then uses that email in an [API call](https://dev.splunk.com/observability/reference/api/organizations/latest#endpoint-retrieve-organization-members) to see if a user in my Splunk organization is associated with that email to then get the unique user id.

**Comment by lindhe** [comment]
I'll try to clarify here what our needs are (I'm working in the same team as Daniel).

We are currently using this provider to setup teams in our SignalFX instance (since SignalFX is missing native integration with groups via OIDC claims). In order to populate the SignalFX team with users, we must have the `userId` for each user that should become a member.

We already have a list of all users for the team, and know the e-mail address for each user. To get the SignalFX `userId`, we are currently using the API that Daniel mentioned, but it would be much better for us if it was available as a Data Source object via the Terraform provider.

I would suggest that the data source should be called something like `signalfx_members` and should return a list or map with all members. We can then filter for the relevant users.

**Comment by atoulme** [comment]
Thank you for this report. I have converted this issue to a Splunk idea: https://ideas.splunk.com/ideas/SFXIMMID-I-626

Please feel free to upvote and comment the Splunk Idea to follow up.
