### ISSUE TITLE
count, for_each or depends_on support while using modules

### ISSUE THREAD

**Issue by pratik141** [splunk-terraform/terraform-provider-signalfx#385]
$  terraform plan

│ Error: Module module.name contains provider configuration
│
│ Providers cannot be configured within modules using count, for_each or depends_on

**Comment by navtej-splunk** [comment]
Hi @pratik141,
Thanks a lot for bringing up the issue. I am PM on this and would love to get more details on this - what steps or custom configuration might have been set. Can you help with more information on this?

Looking forward to hearing from you.
Best,
Navtej

**Comment by pratik-iiss** [comment]
hi @navtej-splunk 
Here is the code and error snippet
## error
$ terraform  init

Initializing the backend...
Initializing modules...
- name in mod
╷
│ Error: Module is incompatible with count, for_each, and depends_on
│ 
│   on main.tf line 4, in module "name":
│    4:   for_each = toset(["asd", "sdds"])
│ 
│ The module at module.name is a legacy module which contains its own local provider configurations, and so calls to it may not use the count, for_each, or depends_on arguments.
│ 
│ If you also control the module "./mod", consider updating this module to instead expect provider configurations to be passed by its caller.
╵
## code
```
 $ cat main.tf 
module "name" {
  source = "./mod"

  for_each = toset(["and", "sdds"])
  appname     = each.name

}
```

### mod/main.tf 
```
resource "signalfx_team" "myteam0" {

  name        = var.appname
  description = "Super great team no jerks definitely"

  members = [
    "userid1",
    "userid2",
    # …
  ]

  notifications_critical = [
    "PagerDuty,credentialId"
  ]

  notifications_info = [
    "Email,notify@example.com"
  ]
}

variable "appname" {


}
```

**Comment by MovieStoreGuy** [comment]
Hey @pratik-iiss,

It looks like this is an issue with your provided configuration, as opposed to a bug in the plugin. If you're still experiencing this issues, it looks like [this article](https://support.hashicorp.com/hc/en-us/articles/21807317486995-Error-Module-is-incompatible-with-count-for-each-and-depends-on) is good overview on how to resolve it.

Otherwise, I ask you to reach out to support and your account team to help you resolve this if the issue is still ongoing.
