### ISSUE TITLE
AWS integration: `enable_aws_usage` state not applying to `true`

### ISSUE THREAD

**Issue by AaronFriel** [splunk-terraform/terraform-provider-signalfx#427]
Hey folks, a user reported this issue on a Pulumi provider we maintain, which bridges this provider:
- https://github.com/pulumi/pulumi-signalfx/issues/215

Digging in to the source code, it looks like the state is always updated from the response `integration.AwsCloudWatchIntegration` response body:
https://github.com/splunk-terraform/terraform-provider-signalfx/blob/fd1fdcf972f4b7c09c3a37f88ed115320e075a17/signalfx/resource_signalfx_aws_integration.go#L312-L314

Can you verify that setting `enableAwsUsage` on the request payload to true will return true on the response, or could we change the behavior of setting the `enable_aws_usage` state to use the input value instead of the response body?

**Comment by akonarska** [comment]
Hey @AaronFriel, the code you pointed to is a correct behaviour. Underneath the provider is calling `v2/integrations` API in Splunk Observability that after creation or update will return the resource that was created. So whatever comes in that payload is a real state that is present.

I looked through the code in the provider and in the signalfx-go (that is making calls to the API) - it looks ok. I tested creating and updating integrations from terraform and I also checked API behaviour - I was not able to reproduce it.

Do you maybe have anything that I can run to reproduce this? Or if there is a scenario reproducing it using pulumi - maybe you (or @jamie1911) could run the API call to get the created integration from there to see what the state really is?

**Comment by AaronFriel** [comment]
@akonarska Can you confirm that `enable_aws_usage` is returning true in your API? I wonder if this is something that might have been fixed on the API since this was created.

**Comment by akonarska** [comment]
@AaronFriel yes, I checked the API as well - it is returning true when set to true, false when set to false. I don't recall us fixing anything around this on the API side. The only thing that comes to mind is that it could have been a hiccup and a fault of our eventual consistent storage, but on the other hand - if it was the storage that should not be so consistent as @jamie1911 reported.
Since you closed the original issue I will now close this one. Feel free to comment if anything new comes up regarding this and we can then reopen it.
