### ISSUE TITLE
Support for "Display Units" in Detectors

### ISSUE THREAD

**Issue by ejwmoreau** [splunk-terraform/terraform-provider-signalfx#43]
Hi :) 
Not sure if this is the right place for this request, but we noticed there's no "Display Units" field for detectors that we can use in Terraform.

I'm not sure if that's because v2 detectors don't support it yet, or if it's something not yet available in the Terraform plugin.

If it's not a v2 detector thing, then what would be the recommended way to display units with the numbers in the detector? It's quite a helpful feature!

**Comment by cory-signalfx** [comment]
Hey @ejwmoreau!

This feature is missing from the API but I agree that it would be a wonderful addition. Unfortunately since this isn't a Terraform feature, this isn't the right place to get it added.

Will close this, but please ping SignalFx support with your request and they'll advise further.

Thanks!

**Comment by ejwmoreau** [comment]
Awesome, thanks! I'll ping SignalFx support with the suggestion :)
