### ISSUE TITLE
Floating point numbers sometimes come back with precision errors

### ISSUE THREAD

**Issue by dmason-atlassian** [splunk-terraform/terraform-provider-signalfx#66]
Sometimes the state fetched from remote will have a floating point rounding error, causing the comparison to the local copy to be mismatched, even though it's not, and thus triggers a change. I've noticed this especially on low_watermark configuration for an axis.

**Comment by mattthebig** [comment]
I'm also getting this problem, I never have a clean plan after applying, horrible for the developer workflow. @cory-signalfx Any progress on getting that PR merged?

**Comment by cory-signalfx** [comment]
Hey @mattthebig, I'm sorry to hear this is interfering with your work. I've not merged this PR mostly because I can't reproduce it and I'm leery of making such a change that isn't reproducible.

I've rebased the PR, could you or @dmason-atlassian perchance try this branch out with the places you are seeing this and report back?

**Comment by cory-signalfx** [comment]
This should be fixed in #174!
