### ISSUE TITLE
Sometimes creating a set of dashboards in a dashboard group doesn't include all dashboards as dashboard configs in the group

### ISSUE THREAD

**Issue by dmason-atlassian** [splunk-terraform/terraform-provider-signalfx#67]
Sometimes, if I create a lot of dashboards in a dashboard group in one terraform command, then despite the dashboard linking back to the group, the dashboard group itself does not contain a dashboard config for that dashboard. This means that the tab for that dashboard does not appear at the top of the screen in the UI. I'm not sure what the trigger for this is, but usually if I destroy and recreate, it will work the next time.

**Comment by cory-signalfx** [comment]
Yeaaaaah, this is a problem wherein some parts of the SignalFx API are frustratingly eventually consistent. We've done some work to mitigate where this happens, but unfortunately the Terraform provider has no ability to fix this.

The only advice I can give (other than perhaps filing a support issue so that this can be properly prioiritized) is to run `apply` with the `--parallelism=1` flag for big batches.

Closing this as wontfix since I can't do anything about it, but with a humble apology!
